version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - gnumap
      - gnumap1
      - gnumap2
      - gnumap3
      - gnumap4
      - gnumap5
      - gnumap6
      - gnumap7
      - gnumap8
      - gnumap9
      - gnumap10
      - gnumap11
  gnumap:
    container_name: gnumap
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap1:
    container_name: gnumap1
    build: ./app
    ports:
      - "8001:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap2:
    container_name: gnumap2
    build: ./app
    ports:
      - "8002:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap3:
    container_name: gnumap3
    build: ./app
    ports:
      - "8003:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap4:
    container_name: gnumap4
    build: ./app
    ports:
      - "8004:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap5:
    container_name: gnumap5
    build: ./app
    ports:
      - "8005:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap6:
    container_name: gnumap6
    build: ./app
    ports:
      - "8006:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap7:
    container_name: gnumap7
    build: ./app
    ports:
      - "8007:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap8:
    container_name: gnumap8
    build: ./app
    ports:
      - "8008:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap9:
    container_name: gnumap9
    build: ./app
    ports:
      - "8009:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnumap10:
    container_name: gnumap10
    build: ./app
    ports:
      - "8010:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
  gnuamp11:
    container_name: gnuamp11
    build: ./app
    ports:
      - "8011:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
volumes:
  logs:
