version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - gnumap
  gnumap:
    container_name: gnumap
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
      - ./env/tmap_gentle.env
volumes:
  logs:
