version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - gnumap
      - gnumap1
      - gnumap2
      - gnumap3
      - gnumap4
      - gnumap5
  gnumap:
    container_name: gnumap
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
      - ./env/tmap_gentle.env
  gnumap1:
    container_name: gnumap1
    build: ./app
    ports:
      - "8001:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
      - ./env/tmap_soyul.env
  gnumap2:
    container_name: gnumap2
    build: ./app
    ports:
      - "8002:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
      - ./env/tmap_gentle.env
  gnumap3:
    container_name: gnumap3
    build: ./app
    ports:
      - "8003:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
      - ./env/tmap_soyul.env
  gnumap4:
    container_name: gnumap4
    build: ./app
    ports:
      - "8004:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
      - ./env/tmap_gentle.env
  gnumap5:
    container_name: gnumap5
    build: ./app
    ports:
      - "8005:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
      - ./env/slack.env
      - ./env/tmap_soyul.env
volumes:
  logs:
