version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/logs
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/db.env
volumes:
  logs:
